# Generated by Django 5.1.5 on 2025-02-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uemail', models.CharField(max_length=20)),
                ('upassword', models.CharField(default='passwd', max_length=20)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
