# Generated by Django 5.1.5 on 2025-02-10 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('aid', models.AutoField(db_column='aid', primary_key=True, serialize=False)),
                ('aname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'artist',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('cid', models.AutoField(db_column='cid', primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('gid', models.AutoField(db_column='gid', primary_key=True, serialize=False)),
                ('gname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('fid', models.AutoField(db_column='fid', primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('city', models.ForeignKey(db_column='cid', on_delete=django.db.models.deletion.CASCADE, to='api.city')),
            ],
            options={
                'db_table': 'festival',
            },
        ),
        migrations.CreateModel(
            name='FestivalArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(db_column='aid', on_delete=django.db.models.deletion.CASCADE, to='api.artist')),
                ('festival', models.ForeignKey(db_column='fid', on_delete=django.db.models.deletion.CASCADE, to='api.festival')),
            ],
            options={
                'db_table': 'festival_artist',
                'unique_together': {('festival', 'artist')},
            },
        ),
        migrations.AddField(
            model_name='festival',
            name='artists',
            field=models.ManyToManyField(related_name='festivals', through='api.FestivalArtist', to='api.artist'),
        ),
        migrations.CreateModel(
            name='ArtistGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(db_column='aid', on_delete=django.db.models.deletion.CASCADE, to='api.artist')),
                ('genre', models.ForeignKey(db_column='gid', on_delete=django.db.models.deletion.CASCADE, to='api.genre')),
            ],
            options={
                'db_table': 'artist_genre',
                'unique_together': {('artist', 'genre')},
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(related_name='artists', through='api.ArtistGenre', to='api.genre'),
        ),
    ]
