# Generated by Django 5.1.6 on 2025-02-10 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_artist_city_genre_festival_festivalartist_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
