# Generated by Django 5.1.5 on 2025-02-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='playlist',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
