# Generated by Django 5.1.5 on 2025-02-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_festival_description_festival_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='uemail',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
