# Generated by Django 5.1.5 on 2025-02-13 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('tid', models.AutoField(db_column='tid', primary_key=True, serialize=False)),
                ('ticket_type', models.CharField(choices=[('Camping', 'Camping'), ('Non-Camping', 'Non-Camping'), ('VIP', 'VIP')], max_length=20)),
                ('ticket_quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('festival', models.ForeignKey(db_column='fid', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.festival')),
                ('user', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.user')),
            ],
        ),
    ]
