# Generated by Django 5.1.5 on 2025-02-13 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type_name', models.CharField(choices=[('Camping', 'Camping'), ('Non-Camping', 'Non-Camping'), ('VIP', 'VIP')], max_length=20, unique=True)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='festival',
            new_name='fid',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='purchase_date',
            new_name='ticket_date',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='user',
            new_name='uid',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_type',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type_name',
            field=models.ForeignKey(db_column='ticket_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tickettype'),
        ),
    ]
