# Generated by Django 5.1.5 on 2025-02-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_tickettype_rename_festival_ticket_fid_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tickettype',
            table='api_tickettype',
        ),
    ]
