# Generated by Django 5.1.5 on 2025-02-14 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_ticket_ticket_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='uid',
        ),
    ]
