# Generated by Django 5.1.5 on 2025-02-14 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_tickettype_id_alter_tickettype_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_type_name',
            new_name='ticket_type_id',
        ),
    ]
