# Generated by Django 5.1.5 on 2025-02-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_ticket_type_name_ticket_ticket_type_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ticket',
            table='ticket',
        ),
    ]
